### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by wireframe**
Sorry about this!  

My first change in #1 was made through the github UI so I didn't have a local ENV to run the testsuite.

NOTE:  automated testsuite w/ travis CI might be a good idea to catch issues like this.

### CODE REVIEW

**Comment by dreamwords** [comment]
Yes, I agree CI should be introduced. On my list now :+1:

**Comment by wireframe** [comment]
the current version in rubygems is busted, and you might want to yank v0.5.4 from rubygems or publish a 0.5.5 version with this fix to prevent anyone from pulling down a bad gem.

**Comment by dreamwords** [comment]
Ryan,

I tried to test in a new project and the current version from rubygems works. Could you please let me know what’s the error you encountered?

Thanks,

-Elan

**Comment by wireframe** [comment]
Try accessing the `deactivated` scope on your devise model and you'll get an error.

ex:

``` ruby
class User < ActiveRecord::Base
  devise :deactivatable
end
```

``` ruby
User.deactivated
#=> User Load (3.5ms)  SELECT "users".* FROM "users" WHERE ("users"."deactivated" IS NOT NULL)
#=> PG::UndefinedColumn: ERROR:  column users.deactivated does not exist
#=> LINE 1: SELECT "users".* FROM "users" WHERE ("users"."deactivated" I...
#=>                                             ^
#=> : SELECT "users".* FROM "users" WHERE ("users"."deactivated" IS NOT NULL)
```

**Comment by wireframe** [comment]
@dreamwords any update?

**Comment by dreamwords** [comment]
I am sorry for the delay, 0.5.5 has been pushed with the patch fixed the typo. Have a try!

Thanks again.

**Pull request merged**
